pragma solidity ^0.5.0;

contract DmmErrorCodes {

    string constant public ALLOWANCE_BELOW_ZERO = "ALLOWANCE_BELOW_ZERO";
    string constant public BLACKLISTED = "BLACKLISTED";
    string constant public BURN_INVALID_ADDRESS = "BURN_INVALID_ADDRESS";
    string constant public BURN_EXCEEDS_ALLOWANCE = "BURN_EXCEEDS_ALLOWANCE";
    string constant public BURN_EXCEEDS_BALANCE = "BURN_EXCEEDS_BALANCE";
    string constant public CANNOT_APPROVE_FROM_ZERO_ADDRESS = "CANNOT_APPROVE_FROM_ZERO_ADDRESS";
    string constant public CANNOT_APPROVE_TO_ZERO_ADDRESS = "CANNOT_APPROVE_TO_ZERO_ADDRESS";
    string constant public CANNOT_MINT_FROM_ZERO_ADDRESS = "CANNOT_MINT_FROM_ZERO_ADDRESS";
    string constant public CANNOT_MINT_TO_ZERO_ADDRESS = "CANNOT_MINT_TO_ZERO_ADDRESS";
    string constant public CANNOT_REDEEM_FROM_ZERO_ADDRESS = "CANNOT_REDEEM_FROM_ZERO_ADDRESS";
    string constant public CANNOT_REDEEM_TO_ZERO_ADDRESS = "CANNOT_REDEEM_TO_ZERO_ADDRESS";
    string constant public CANNOT_TRANSFER_FROM_ZERO_ADDRESS = "CANNOT_TRANSFER_FROM_ZERO_ADDRESS";
    string constant public CANNOT_TRANSFER_TO_ZERO_ADDRESS = "CANNOT_TRANSFER_TO_ZERO_ADDRESS";
    string constant public ECOSYSTEM_ALREADY_PAUSED = "ECOSYSTEM_ALREADY_PAUSED";
    string constant public ECOSYSTEM_MUST_BE_PAUSED = "ECOSYSTEM_MUST_BE_PAUSED";
    string constant public ECOSYSTEM_PAUSED = "ECOSYSTEM_PAUSED";
    string constant public FEE_TOO_LARGE = "FEE_TOO_LARGE";
    string constant public INSUFFICIENT_COLLATERAL = "INSUFFICIENT_COLLATERAL";
    string constant public INSUFFICIENT_DMM_LIQUIDITY = "INSUFFICIENT_DMM_LIQUIDITY";
    string constant public INSUFFICIENT_MINT_AMOUNT = "INSUFFICIENT_MINT_AMOUNT";
    string constant public INSUFFICIENT_REDEEM_AMOUNT = "INSUFFICIENT_REDEEM_AMOUNT";
    string constant public INSUFFICIENT_UNDERLYING_LIQUIDITY = "INSUFFICIENT_UNDERLYING_LIQUIDITY";
    string constant public INSUFFICIENT_LEFTOVER_RESERVES = "INSUFFICIENT_LEFTOVER_RESERVES";
    string constant public INVALID_ADMIN = "INVALID_ADMIN";
    string constant public INVALID_BLACKLISTER = "INVALID_BLACKLISTER";
    string constant public INVALID_BLOCK_TIMESTAMP = "INVALID_BLOCK_TIMESTAMP";
    string constant public INVALID_FEE_ADDRESS = "INVALID_FEE_ADDRESS";
    string constant public INVALID_NONCE = "INVALID_NONCE";
    string constant public INVALID_OWNER = "INVALID_OWNER";
    string constant public INVALID_SIGNATURE = "INVALID_SIGNATURE";
    string constant public MARKET_DISABLED = "MARKET_DISABLED";
    string constant public MARKET_ALREADY_DISABLED = "MARKET_ALREADY_DISABLED";
    string constant public MARKET_ALREADY_ENABLED = "MARKET_ALREADY_ENABLED";
    string constant public MINT_EXCEEDS_ALLOWANCE = "MINT_EXCEEDS_ALLOWANCE";
    string constant public MUST_BE_BLACKLISTER = "MUST_BE_BLACKLISTER";
    string constant public NO_DEFAULT_FUNCTION = "NO_DEFAULT_FUNCTION";
    string constant public REDEEM_EXCEEDS_ALLOWANCE = "REDEEM_EXCEEDS_ALLOWANCE";
    string constant public REQUEST_EXPIRED = "REQUEST_EXPIRED";
    string constant public TOO_MUCH_ACTIVE_SUPPLY = "TOO_MUCH_ACTIVE_SUPPLY";
    string constant public TOKEN_DOES_NOT_EXIST = "TOKEN_DOES_NOT_EXIST";
    string constant public TRANSFER_EXCEEDS_ALLOWANCE = "TRANSFER_EXCEEDS_ALLOWANCE";
    string constant public TRANSFER_EXCEEDS_BALANCE = "TRANSFER_EXCEEDS_BALANCE";

}